// Code generated by scripts/generate-ios-vt.py; DO NOT EDIT.
//go:build ios && cgo

package vt

/*
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
extern void ghostty_focus_encode(void);
extern void ghostty_formatter_format_alloc(void);
extern void ghostty_formatter_free(void);
extern void ghostty_formatter_terminal_new(void);
extern void ghostty_free(void);
extern void ghostty_grid_ref_cell(void);
extern void ghostty_grid_ref_graphemes(void);
extern void ghostty_grid_ref_hyperlink_uri(void);
extern void ghostty_key_encoder_encode(void);
extern void ghostty_key_encoder_free(void);
extern void ghostty_key_encoder_new(void);
extern void ghostty_key_encoder_setopt(void);
extern void ghostty_key_encoder_setopt_from_terminal(void);
extern void ghostty_key_event_free(void);
extern void ghostty_key_event_new(void);
extern void ghostty_key_event_set_action(void);
extern void ghostty_key_event_set_composing(void);
extern void ghostty_key_event_set_consumed_mods(void);
extern void ghostty_key_event_set_key(void);
extern void ghostty_key_event_set_mods(void);
extern void ghostty_key_event_set_unshifted_codepoint(void);
extern void ghostty_key_event_set_utf8(void);
extern void ghostty_mouse_encoder_encode(void);
extern void ghostty_mouse_encoder_free(void);
extern void ghostty_mouse_encoder_new(void);
extern void ghostty_mouse_encoder_reset(void);
extern void ghostty_mouse_encoder_setopt(void);
extern void ghostty_mouse_encoder_setopt_from_terminal(void);
extern void ghostty_mouse_event_clear_button(void);
extern void ghostty_mouse_event_free(void);
extern void ghostty_mouse_event_new(void);
extern void ghostty_mouse_event_set_action(void);
extern void ghostty_mouse_event_set_button(void);
extern void ghostty_mouse_event_set_mods(void);
extern void ghostty_mouse_event_set_position(void);
extern void ghostty_paste_encode(void);
extern void ghostty_paste_is_safe(void);
extern void ghostty_render_state_begin_update(void);
extern void ghostty_render_state_clean(void);
extern void ghostty_render_state_end_update(void);
extern void ghostty_render_state_free(void);
extern void ghostty_render_state_get(void);
extern void ghostty_render_state_new(void);
extern void ghostty_render_state_row_cells_free(void);
extern void ghostty_render_state_row_cells_get(void);
extern void ghostty_render_state_row_cells_new(void);
extern void ghostty_render_state_row_cells_select(void);
extern void ghostty_render_state_row_get(void);
extern void ghostty_render_state_row_iterator_free(void);
extern void ghostty_render_state_row_iterator_new(void);
extern void ghostty_render_state_row_iterator_next(void);
extern void ghostty_search_feed(void);
extern void ghostty_search_free(void);
extern void ghostty_search_get(void);
extern void ghostty_search_new(void);
extern void ghostty_search_set(void);
extern void ghostty_search_tick(void);
extern void ghostty_selection_gesture_event(void);
extern void ghostty_selection_gesture_event_free(void);
extern void ghostty_selection_gesture_event_new(void);
extern void ghostty_selection_gesture_event_set(void);
extern void ghostty_selection_gesture_free(void);
extern void ghostty_selection_gesture_get(void);
extern void ghostty_selection_gesture_new(void);
extern void ghostty_selection_gesture_reset(void);
extern void ghostty_terminal_compress(void);
extern void ghostty_terminal_compression_activity(void);
extern void ghostty_terminal_free(void);
extern void ghostty_terminal_get(void);
extern void ghostty_terminal_grid_ref(void);
extern void ghostty_terminal_new(void);
extern void ghostty_terminal_point_from_grid_ref(void);
extern void ghostty_terminal_reset(void);
extern void ghostty_terminal_resize(void);
extern void ghostty_terminal_scroll_viewport(void);
extern void ghostty_terminal_select_all(void);
extern void ghostty_terminal_selection_format_alloc(void);
extern void ghostty_terminal_set(void);
extern void ghostty_terminal_vt_write(void);
extern void ghostty_type_json(void);
static uintptr_t gorex_vt_symbol(const char *name) {
 if (!strcmp(name,"ghostty_focus_encode")) return (uintptr_t)&ghostty_focus_encode;
 if (!strcmp(name,"ghostty_formatter_format_alloc")) return (uintptr_t)&ghostty_formatter_format_alloc;
 if (!strcmp(name,"ghostty_formatter_free")) return (uintptr_t)&ghostty_formatter_free;
 if (!strcmp(name,"ghostty_formatter_terminal_new")) return (uintptr_t)&ghostty_formatter_terminal_new;
 if (!strcmp(name,"ghostty_free")) return (uintptr_t)&ghostty_free;
 if (!strcmp(name,"ghostty_grid_ref_cell")) return (uintptr_t)&ghostty_grid_ref_cell;
 if (!strcmp(name,"ghostty_grid_ref_graphemes")) return (uintptr_t)&ghostty_grid_ref_graphemes;
 if (!strcmp(name,"ghostty_grid_ref_hyperlink_uri")) return (uintptr_t)&ghostty_grid_ref_hyperlink_uri;
 if (!strcmp(name,"ghostty_key_encoder_encode")) return (uintptr_t)&ghostty_key_encoder_encode;
 if (!strcmp(name,"ghostty_key_encoder_free")) return (uintptr_t)&ghostty_key_encoder_free;
 if (!strcmp(name,"ghostty_key_encoder_new")) return (uintptr_t)&ghostty_key_encoder_new;
 if (!strcmp(name,"ghostty_key_encoder_setopt")) return (uintptr_t)&ghostty_key_encoder_setopt;
 if (!strcmp(name,"ghostty_key_encoder_setopt_from_terminal")) return (uintptr_t)&ghostty_key_encoder_setopt_from_terminal;
 if (!strcmp(name,"ghostty_key_event_free")) return (uintptr_t)&ghostty_key_event_free;
 if (!strcmp(name,"ghostty_key_event_new")) return (uintptr_t)&ghostty_key_event_new;
 if (!strcmp(name,"ghostty_key_event_set_action")) return (uintptr_t)&ghostty_key_event_set_action;
 if (!strcmp(name,"ghostty_key_event_set_composing")) return (uintptr_t)&ghostty_key_event_set_composing;
 if (!strcmp(name,"ghostty_key_event_set_consumed_mods")) return (uintptr_t)&ghostty_key_event_set_consumed_mods;
 if (!strcmp(name,"ghostty_key_event_set_key")) return (uintptr_t)&ghostty_key_event_set_key;
 if (!strcmp(name,"ghostty_key_event_set_mods")) return (uintptr_t)&ghostty_key_event_set_mods;
 if (!strcmp(name,"ghostty_key_event_set_unshifted_codepoint")) return (uintptr_t)&ghostty_key_event_set_unshifted_codepoint;
 if (!strcmp(name,"ghostty_key_event_set_utf8")) return (uintptr_t)&ghostty_key_event_set_utf8;
 if (!strcmp(name,"ghostty_mouse_encoder_encode")) return (uintptr_t)&ghostty_mouse_encoder_encode;
 if (!strcmp(name,"ghostty_mouse_encoder_free")) return (uintptr_t)&ghostty_mouse_encoder_free;
 if (!strcmp(name,"ghostty_mouse_encoder_new")) return (uintptr_t)&ghostty_mouse_encoder_new;
 if (!strcmp(name,"ghostty_mouse_encoder_reset")) return (uintptr_t)&ghostty_mouse_encoder_reset;
 if (!strcmp(name,"ghostty_mouse_encoder_setopt")) return (uintptr_t)&ghostty_mouse_encoder_setopt;
 if (!strcmp(name,"ghostty_mouse_encoder_setopt_from_terminal")) return (uintptr_t)&ghostty_mouse_encoder_setopt_from_terminal;
 if (!strcmp(name,"ghostty_mouse_event_clear_button")) return (uintptr_t)&ghostty_mouse_event_clear_button;
 if (!strcmp(name,"ghostty_mouse_event_free")) return (uintptr_t)&ghostty_mouse_event_free;
 if (!strcmp(name,"ghostty_mouse_event_new")) return (uintptr_t)&ghostty_mouse_event_new;
 if (!strcmp(name,"ghostty_mouse_event_set_action")) return (uintptr_t)&ghostty_mouse_event_set_action;
 if (!strcmp(name,"ghostty_mouse_event_set_button")) return (uintptr_t)&ghostty_mouse_event_set_button;
 if (!strcmp(name,"ghostty_mouse_event_set_mods")) return (uintptr_t)&ghostty_mouse_event_set_mods;
 if (!strcmp(name,"ghostty_mouse_event_set_position")) return (uintptr_t)&ghostty_mouse_event_set_position;
 if (!strcmp(name,"ghostty_paste_encode")) return (uintptr_t)&ghostty_paste_encode;
 if (!strcmp(name,"ghostty_paste_is_safe")) return (uintptr_t)&ghostty_paste_is_safe;
 if (!strcmp(name,"ghostty_render_state_begin_update")) return (uintptr_t)&ghostty_render_state_begin_update;
 if (!strcmp(name,"ghostty_render_state_clean")) return (uintptr_t)&ghostty_render_state_clean;
 if (!strcmp(name,"ghostty_render_state_end_update")) return (uintptr_t)&ghostty_render_state_end_update;
 if (!strcmp(name,"ghostty_render_state_free")) return (uintptr_t)&ghostty_render_state_free;
 if (!strcmp(name,"ghostty_render_state_get")) return (uintptr_t)&ghostty_render_state_get;
 if (!strcmp(name,"ghostty_render_state_new")) return (uintptr_t)&ghostty_render_state_new;
 if (!strcmp(name,"ghostty_render_state_row_cells_free")) return (uintptr_t)&ghostty_render_state_row_cells_free;
 if (!strcmp(name,"ghostty_render_state_row_cells_get")) return (uintptr_t)&ghostty_render_state_row_cells_get;
 if (!strcmp(name,"ghostty_render_state_row_cells_new")) return (uintptr_t)&ghostty_render_state_row_cells_new;
 if (!strcmp(name,"ghostty_render_state_row_cells_select")) return (uintptr_t)&ghostty_render_state_row_cells_select;
 if (!strcmp(name,"ghostty_render_state_row_get")) return (uintptr_t)&ghostty_render_state_row_get;
 if (!strcmp(name,"ghostty_render_state_row_iterator_free")) return (uintptr_t)&ghostty_render_state_row_iterator_free;
 if (!strcmp(name,"ghostty_render_state_row_iterator_new")) return (uintptr_t)&ghostty_render_state_row_iterator_new;
 if (!strcmp(name,"ghostty_render_state_row_iterator_next")) return (uintptr_t)&ghostty_render_state_row_iterator_next;
 if (!strcmp(name,"ghostty_search_feed")) return (uintptr_t)&ghostty_search_feed;
 if (!strcmp(name,"ghostty_search_free")) return (uintptr_t)&ghostty_search_free;
 if (!strcmp(name,"ghostty_search_get")) return (uintptr_t)&ghostty_search_get;
 if (!strcmp(name,"ghostty_search_new")) return (uintptr_t)&ghostty_search_new;
 if (!strcmp(name,"ghostty_search_set")) return (uintptr_t)&ghostty_search_set;
 if (!strcmp(name,"ghostty_search_tick")) return (uintptr_t)&ghostty_search_tick;
 if (!strcmp(name,"ghostty_selection_gesture_event")) return (uintptr_t)&ghostty_selection_gesture_event;
 if (!strcmp(name,"ghostty_selection_gesture_event_free")) return (uintptr_t)&ghostty_selection_gesture_event_free;
 if (!strcmp(name,"ghostty_selection_gesture_event_new")) return (uintptr_t)&ghostty_selection_gesture_event_new;
 if (!strcmp(name,"ghostty_selection_gesture_event_set")) return (uintptr_t)&ghostty_selection_gesture_event_set;
 if (!strcmp(name,"ghostty_selection_gesture_free")) return (uintptr_t)&ghostty_selection_gesture_free;
 if (!strcmp(name,"ghostty_selection_gesture_get")) return (uintptr_t)&ghostty_selection_gesture_get;
 if (!strcmp(name,"ghostty_selection_gesture_new")) return (uintptr_t)&ghostty_selection_gesture_new;
 if (!strcmp(name,"ghostty_selection_gesture_reset")) return (uintptr_t)&ghostty_selection_gesture_reset;
 if (!strcmp(name,"ghostty_terminal_compress")) return (uintptr_t)&ghostty_terminal_compress;
 if (!strcmp(name,"ghostty_terminal_compression_activity")) return (uintptr_t)&ghostty_terminal_compression_activity;
 if (!strcmp(name,"ghostty_terminal_free")) return (uintptr_t)&ghostty_terminal_free;
 if (!strcmp(name,"ghostty_terminal_get")) return (uintptr_t)&ghostty_terminal_get;
 if (!strcmp(name,"ghostty_terminal_grid_ref")) return (uintptr_t)&ghostty_terminal_grid_ref;
 if (!strcmp(name,"ghostty_terminal_new")) return (uintptr_t)&ghostty_terminal_new;
 if (!strcmp(name,"ghostty_terminal_point_from_grid_ref")) return (uintptr_t)&ghostty_terminal_point_from_grid_ref;
 if (!strcmp(name,"ghostty_terminal_reset")) return (uintptr_t)&ghostty_terminal_reset;
 if (!strcmp(name,"ghostty_terminal_resize")) return (uintptr_t)&ghostty_terminal_resize;
 if (!strcmp(name,"ghostty_terminal_scroll_viewport")) return (uintptr_t)&ghostty_terminal_scroll_viewport;
 if (!strcmp(name,"ghostty_terminal_select_all")) return (uintptr_t)&ghostty_terminal_select_all;
 if (!strcmp(name,"ghostty_terminal_selection_format_alloc")) return (uintptr_t)&ghostty_terminal_selection_format_alloc;
 if (!strcmp(name,"ghostty_terminal_set")) return (uintptr_t)&ghostty_terminal_set;
 if (!strcmp(name,"ghostty_terminal_vt_write")) return (uintptr_t)&ghostty_terminal_vt_write;
 if (!strcmp(name,"ghostty_type_json")) return (uintptr_t)&ghostty_type_json;
 return 0;
}
*/
import "C"

import (
	"fmt"
	"unsafe"
)

func open(string) (uintptr, error) { return 1, nil }
func sym(_ uintptr, name string) (uintptr, error) {
	s := C.CString(name)
	defer C.free(unsafe.Pointer(s))
	address := uintptr(C.gorex_vt_symbol(s))
	if address == 0 {
		return 0, fmt.Errorf("vt: missing linked symbol %s", name)
	}
	return address, nil
}
