#!/usr/bin/env python3
"""Keep the iOS static symbol table in sync with the shared VT bindings."""
from pathlib import Path
import re
root = Path(__file__).resolve().parent.parent
vt = root / 'internal/terminal/internal/vt'
symbols = sorted({name for path in vt.glob('*.go')
                  if not path.name.startswith('open_') and not path.name.endswith('_test.go')
                  for name in re.findall(r'"(ghostty_\w+)"', path.read_text())})
header = '''// Code generated by scripts/generate-ios-vt.py; DO NOT EDIT.
//go:build ios && cgo

package vt

/*
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
'''
body = '\n'.join('extern void '+name+'(void);' for name in symbols)
body += '\nstatic uintptr_t gorex_vt_symbol(const char *name) {\n'
body += '\n'.join(' if (!strcmp(name,"'+name+'")) return (uintptr_t)&'+name+';' for name in symbols)
footer = '''
 return 0;
}
*/
import "C"

import (
 "fmt"
 "unsafe"
)

func open(string) (uintptr, error) { return 1, nil }
func sym(_ uintptr, name string) (uintptr, error) {
 s := C.CString(name)
 defer C.free(unsafe.Pointer(s))
 address := uintptr(C.gorex_vt_symbol(s))
 if address == 0 { return 0, fmt.Errorf("vt: missing linked symbol %s", name) }
 return address, nil
}
'''
(vt/'open_ios.go').write_text(header+body+footer)
